name: BlueMapPlayerControl
version: '${project.version}'
main: com.technicjelle.bluemapplayercontrol.BlueMapPlayerControl
folia-supported: true
api-version: 1.13
depend:
  - BlueMap
author: TechnicJelle
description: Adds player hiding functionality to BlueMap
website: https://github.com/TechnicJelle/BlueMapPlayerControl

commands:
  map:
    usage: /<command> [hide | show | toggle] [player]
    description: Online map
    permission: map
permissions:
  map:
    default: true
  map.*:
    default: op
    children:
      map.self:
        default: false
        children:
          map.self.toggle: false
          map.self.show: false
          map.self.hide: false
      map.others:
        default: op
        children:
          map.others.toggle: true
          map.others.show: true
          map.others.hide: true
  map.self.toggle:
    default: false
  map.self.show:
    default: false
  map.self.hide:
    default: false
  map.others.toggle:
    default: op
  map.others.show:
    default: op
  map.others.hide:
    default: op
